/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdministrativeRole;

import Business.Enterprise.Enterprise;
import Business.Enterprise.EnterpriseDirectory;
import Business.Requirement.Requirement;
import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.UIManager;

/**
 *
 * @author Eshanee Thakur
 */
public class AdminReportsJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    EnterpriseDirectory enterpriseDirectory;

    /**
     * Creates new form AdminReportsJPanel
     */
    public AdminReportsJPanel(JPanel userProcessContainer, EnterpriseDirectory directory) {
        initComponents();
        this.enterpriseDirectory = directory;
        this.userProcessContainer = userProcessContainer;

        populateGraph();
    }

    public void populateGraph() {

        //GOODS COLLECTED TILL NOW
        int maxFoodCategoryRequirement = 0;
        int foodCategoryCollected = 0;
        int maxMedicinesCategoryRequirement = 0;
        int medicinesCategoryCollected = 0;
        int maxClothesCategoryRequirement = 0;
        int clothesCategoryCollected = 0;
        int maxAmenitiesCategoryRequirement = 0;
        int amenitiesCategoryCollected = 0;

        for (Enterprise ent : enterpriseDirectory.getEnterpriseList()) {
            if (ent.getEnterpriseType().toString().equalsIgnoreCase(Enterprise.EnterpriseType.NGO.getValue())) {
                for (Requirement req : ent.getRequirementDirectory().getRequirementDirectory()) {
                    if (req.getCategory().equalsIgnoreCase("food")) {
                        foodCategoryCollected += req.getCollectedCount();
                        maxFoodCategoryRequirement += req.getInitialRequirementCount();
                    }
                    if (req.getCategory().equalsIgnoreCase("medicines")) {
                        medicinesCategoryCollected += req.getCollectedCount();
                        maxMedicinesCategoryRequirement += req.getInitialRequirementCount();
                    }
                    if (req.getCategory().equalsIgnoreCase("clothes")) {
                        clothesCategoryCollected += req.getCollectedCount();
                        maxClothesCategoryRequirement += req.getInitialRequirementCount();
                    }
                    if (req.getCategory().equalsIgnoreCase("BasicAmenities")) {
                        amenitiesCategoryCollected += req.getCollectedCount();
                        maxAmenitiesCategoryRequirement += req.getInitialRequirementCount();
                    }
                }
            }
        }
        prgbarFood.setMaximum(maxFoodCategoryRequirement);
        prgbarFood.setValue(foodCategoryCollected);
        lblFood.setText(foodCategoryCollected + "/" + maxFoodCategoryRequirement);

        prgbarMedicines.setMaximum(maxMedicinesCategoryRequirement);
        prgbarMedicines.setValue(medicinesCategoryCollected);
        lblMeds.setText(medicinesCategoryCollected + "/" + maxMedicinesCategoryRequirement);

        prgbarClothes.setMaximum(maxClothesCategoryRequirement);
        prgbarClothes.setValue(clothesCategoryCollected);
        lblClothes.setText(clothesCategoryCollected + "/" + maxClothesCategoryRequirement);

        prgbarAmenities.setMaximum(maxAmenitiesCategoryRequirement);
        prgbarAmenities.setValue(amenitiesCategoryCollected);
        lblBasic.setText(amenitiesCategoryCollected + "/" + maxAmenitiesCategoryRequirement);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prgbarFood = new javax.swing.JProgressBar();
        prgbarMedicines = new javax.swing.JProgressBar();
        prgbarClothes = new javax.swing.JProgressBar();
        prgbarAmenities = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblFood = new javax.swing.JLabel();
        lblMeds = new javax.swing.JLabel();
        lblClothes = new javax.swing.JLabel();
        lblBasic = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        prgbarFood.setBackground(new java.awt.Color(255, 255, 255));
        prgbarFood.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        prgbarFood.setForeground(new java.awt.Color(0, 153, 255));

        prgbarMedicines.setBackground(new java.awt.Color(255, 255, 255));
        prgbarMedicines.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        prgbarMedicines.setForeground(new java.awt.Color(0, 153, 255));

        prgbarClothes.setBackground(new java.awt.Color(255, 255, 255));
        prgbarClothes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        prgbarClothes.setForeground(new java.awt.Color(0, 153, 255));

        prgbarAmenities.setBackground(new java.awt.Color(255, 255, 255));
        prgbarAmenities.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        prgbarAmenities.setForeground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("Requirement Dashboard");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Food");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Requirement Progress based on categories:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Medicines");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Clothes");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Basic Amenities");

        lblFood.setBackground(new java.awt.Color(255, 255, 255));
        lblFood.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFood.setText("--");

        lblMeds.setBackground(new java.awt.Color(255, 255, 255));
        lblMeds.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMeds.setText("--");

        lblClothes.setBackground(new java.awt.Color(255, 255, 255));
        lblClothes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblClothes.setText("--");

        lblBasic.setBackground(new java.awt.Color(255, 255, 255));
        lblBasic.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBasic.setText("--");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(prgbarAmenities, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(prgbarClothes, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(prgbarMedicines, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(prgbarFood, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFood, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBasic, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMeds, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblClothes, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(462, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblFood, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                            .addComponent(prgbarFood, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prgbarMedicines, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMeds, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblClothes, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblBasic, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(prgbarClothes, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(prgbarAmenities, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(252, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblBasic;
    private javax.swing.JLabel lblClothes;
    private javax.swing.JLabel lblFood;
    private javax.swing.JLabel lblMeds;
    private javax.swing.JProgressBar prgbarAmenities;
    private javax.swing.JProgressBar prgbarClothes;
    private javax.swing.JProgressBar prgbarFood;
    private javax.swing.JProgressBar prgbarMedicines;
    // End of variables declaration//GEN-END:variables
}
