/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.TransporterRole;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.HumanResource;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CollectionWorkRequest;
import Business.WorkQueue.PackageDeliveryWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Eshanee Thakur
 */
public class PackageDeliveryJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    CollectionWorkRequest request;
    UserAccount userAccount;
    Enterprise enterprise;
    Network network;
    private ArrayList<WorkRequest> requestList;

    /**
     * Creates new form PackageDeliveryJPanel
     */
    public PackageDeliveryJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, Network network, ArrayList<WorkRequest> selectedRows) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.network = network;
        this.requestList = selectedRows;

        txtDestination.setText(requestList.get(0).getArea());//Same destination requests allowed

        //Load the list
        for (WorkRequest req : requestList) {
            textAreaRequests.append(req.getItemName() + " : " + req.getItemCount() + "\n");
        }

    }

    public void backToMainScreen() {
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        TransporterWorkAreaJPanel tjp = (TransporterWorkAreaJPanel) component;
        tjp.populateDeliveryRequestTable();
        tjp.populateDeliveryProgressTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDriver = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTime = new javax.swing.JTextField();
        btnDeliver = new javax.swing.JButton();
        txtDestination = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        textAreaRequests = new java.awt.TextArea();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("READY FOR DELIVERY");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Shipment Requests :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Driver Name:");

        txtDriver.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Car Number:");

        txtCar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Estimated Arrival Date (dd/MM/yyyy) :");

        txtTime.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimeActionPerformed(evt);
            }
        });

        btnDeliver.setBackground(new java.awt.Color(0, 153, 255));
        btnDeliver.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDeliver.setForeground(new java.awt.Color(255, 255, 255));
        btnDeliver.setText("On the way");
        btnDeliver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeliverActionPerformed(evt);
            }
        });

        txtDestination.setEditable(false);
        txtDestination.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Destination:");

        backJButton.setBackground(new java.awt.Color(0, 153, 255));
        backJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        textAreaRequests.setEditable(false);
        textAreaRequests.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backJButton)
                        .addGap(126, 126, 126)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(200, 200, 200)
                            .addComponent(btnDeliver, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(171, 171, 171)
                            .addComponent(textAreaRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(370, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton)
                    .addComponent(jLabel1))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(textAreaRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(33, 33, 33)
                .addComponent(btnDeliver)
                .addGap(91, 91, 91))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeliverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeliverActionPerformed
        String validationMsg = "";
        if (txtDriver.getText() == null || txtDriver.getText().isEmpty() || txtDriver.getText().trim().isEmpty()) {
            validationMsg = "Driver name can't be empty.\n";
        }
        if (txtCar.getText() == null || txtCar.getText().isEmpty() || txtCar.getText().trim().isEmpty()) {
            validationMsg = "Car number can't be empty.\n";
        }
        if (txtTime.getText() == null || txtTime.getText().isEmpty() || txtTime.getText().trim().isEmpty()) {
            validationMsg += "Estimated arrival date can't be empty.\n";
        } else {
            String format = "dd/MM/yyyy";
            SimpleDateFormat sdf = new SimpleDateFormat(format);
            sdf.setLenient(false);
            Date currentDate = new Date();
            try {
                Date arrDate = sdf.parse((txtTime.getText()));
                currentDate = sdf.parse(sdf.format(currentDate));
                if (currentDate.compareTo(arrDate) > 0) {
                    validationMsg += "Arrival date can't be past dated.\n";
                    txtTime.setText("");
                }
            } catch (Exception e) {
                validationMsg += "Please enter date in the following format -(dd/MM/yyyy)\n";
                txtTime.setText("");
            }
        }

        if (!validationMsg.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please review the below error(s):\n" + validationMsg);
            return;
        }

        String carNumber = txtCar.getText();
        String driverName = txtDriver.getText();
        String estimatedTime = txtTime.getText();
        String destination = txtDestination.getText();

        for (WorkRequest req : requestList) {
            req.setStatus("On the way");
        }

        PackageDeliveryWorkRequest deliveryRequest = new PackageDeliveryWorkRequest(requestList);
        deliveryRequest.setDestination(destination);
        deliveryRequest.setCarNumber(carNumber);
        deliveryRequest.setDriverName(driverName);
        deliveryRequest.setEstimatedTime(estimatedTime);
        deliveryRequest.setPackageName(destination + "_" + new Date());
        deliveryRequest.setRequestDate(new Date());
        deliveryRequest.setSender(userAccount);
        deliveryRequest.setStatus("On the way");

        Organization org = null;
        for (Enterprise ent : network.getEnterpriseDirectory().getEnterpriseList()) {
            for (Organization organization : ent.getOrganizationDirectory().getOrganizationList()) {
                if (organization instanceof HumanResource) {
                    org = organization;
                    break;
                }
            }
        }
        if (org != null) {
            org.getWorkQueue().getWorkRequestList().add(deliveryRequest);
            userAccount.getWorkQueue().getWorkRequestList().add(deliveryRequest);
        }

        JOptionPane.showMessageDialog(null, "Package is on the way.");

        backToMainScreen();
    }//GEN-LAST:event_btnDeliverActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        backToMainScreen();
    }//GEN-LAST:event_backJButtonActionPerformed

    private void txtTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnDeliver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private java.awt.TextArea textAreaRequests;
    private javax.swing.JTextField txtCar;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JTextField txtDriver;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables
}
