/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.AirlinerDirectory;
import Business.CustomerDirectory;
import Business.FlightDirectory;
import Business.Users.Admin;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author Eshanee Thakur
 */
public class AdminMainScreen extends javax.swing.JPanel {

    /**
     * Creates new form AdminMainScreen
     */
    private Admin admin;
    private JPanel panelRight;
    private AirlinerDirectory airlinerDir;
    private FlightDirectory flightdir;
    private CustomerDirectory customerDirectory;

    public AdminMainScreen(JPanel panelRight, Admin admin, AirlinerDirectory airlinerDir, FlightDirectory flightDir, CustomerDirectory customerDirectory) {
        initComponents();
        this.admin = admin;
        this.panelRight = panelRight;
        this.airlinerDir = airlinerDir;
        this.flightdir = flightDir;
        this.customerDirectory = customerDirectory;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    /*  private void logoutJButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        
          CardLayout layout = (CardLayout)panelRight.getLayout();
             panelRight.add(new LoginScreen(panelRight));
               layout.next(panelRight); 
        
        logoutJButton.setEnabled(false);
        userNameJTextField.setEnabled(true);
        passwordField.setEnabled(true);
        loginJButton.setEnabled(true);

        userNameJTextField.setText("");
        passwordField.setText("");


      panelRight.removeAll();
      JPanel blankJP = new JPanel();
        panelRight.add("blank", blankJP);
        CardLayout crdLyt = (CardLayout) panelRight.getLayout();
        crdLyt.next(panelRight);
    

               
    }  */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerBtn = new javax.swing.JButton();
        airlinerBtn = new javax.swing.JButton();
        FleetBtn = new javax.swing.JButton();
        SearchBtn = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        customerBtn.setText("Customer");
        customerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerBtnActionPerformed(evt);
            }
        });

        airlinerBtn.setText("Airliner");
        airlinerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airlinerBtnActionPerformed(evt);
            }
        });

        FleetBtn.setText("Fleet");
        FleetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FleetBtnActionPerformed(evt);
            }
        });

        SearchBtn.setText("Search");
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });

        btnLogout.setText("Log out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(customerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FleetBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(airlinerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SearchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLogout)))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogout)
                .addGap(13, 13, 13)
                .addComponent(customerBtn)
                .addGap(18, 18, 18)
                .addComponent(airlinerBtn)
                .addGap(27, 27, 27)
                .addComponent(FleetBtn)
                .addGap(18, 18, 18)
                .addComponent(SearchBtn)
                .addContainerGap(94, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void airlinerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airlinerBtnActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) this.panelRight.getLayout();
        panelRight.add(new ManageAirliner(this.panelRight, airlinerDir));
        layout.next(panelRight);
    }//GEN-LAST:event_airlinerBtnActionPerformed

    private void FleetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FleetBtnActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) this.panelRight.getLayout();
        panelRight.add(new ManageFleet(this.panelRight, flightdir, airlinerDir));
        layout.next(panelRight);
    }//GEN-LAST:event_FleetBtnActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) this.panelRight.getLayout();
        panelRight.add(new Admin_Search(this.panelRight, flightdir, airlinerDir));
        layout.next(panelRight);
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void customerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerBtnActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) this.panelRight.getLayout();
        panelRight.add(new CreateCustomer(this.panelRight, admin, customerDirectory));
        layout.next(panelRight);
    }//GEN-LAST:event_customerBtnActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        this.panelRight.remove(this);
        CardLayout layout = (CardLayout) this.panelRight.getLayout();

        Component[] comps = MainFrame.getFrames();
        for (Component comp : comps) {
            if (comp instanceof MainFrame) {
                MainFrame mainFrame = (MainFrame) comp;
                mainFrame.initialize();
            }
        }

        layout.previous(panelRight);
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FleetBtn;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JButton airlinerBtn;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton customerBtn;
    // End of variables declaration//GEN-END:variables
}
