/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Booking;
import Business.BookingDirectory;
import Business.Flight;
import Business.Users.Customer;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Eshanee Thakur
 */
public class CustomerBookFlight extends javax.swing.JPanel {

    /**
     * Creates new form CustomerBookFlight
     */
    private JPanel rightPanel;
    private Flight flight;
    private Customer customer;
    private BookingDirectory bookingDirectory;

    //Seat row allocation arrays
    public CustomerBookFlight() {
        initComponents();
    }

    public CustomerBookFlight(JPanel rightPanel, Flight flight, Customer customer, BookingDirectory bookingDirectory) {
        initComponents();
        this.rightPanel = rightPanel;
        this.customer = customer;
        this.flight = flight;
        this.bookingDirectory = bookingDirectory;

        populateDetails();

    }

    public void populateDetails() {
        txtAirliner.setText(flight.getAirliner().getAirLinerName());
        txtFlightNo.setText(flight.getFlightID());
        txtSource.setText(flight.getSource());
        txtDestination.setText(flight.getDestination());
        txtArrTime.setText(flight.getArrival());
        txtDeptTime.setText(flight.getDeparture());
        txtPrice.setText(String.valueOf(flight.getFlightcharges()));
        txtHalts.setText(String.valueOf(flight.getHalts()));
        txtDate.setText(flight.getDate());

        txtUsername.setText(customer.getUsername());
        txtBookingDate.setText(String.valueOf(new Date()));

        drpdwnSeatColumn.removeAllItems();
        drpdwnSeatRow.removeAllItems();

        txtSelectedSeat.setText("");

    }

    public boolean emailIDPatternCorrect() {
        Pattern p = Pattern.compile("^[a-zA-Z0-9]+_[a-zA-Z0-9]+@[a-zA-Z0-9]+.[a-zA-Z0-9]+$");
        Matcher m = p.matcher(txtEmailID.getText());
        return m.matches();
    }

    public boolean phonePatternCorrect() {
        Pattern p = Pattern.compile("^(?=.*\\d).{8,10}$");
        Matcher m = p.matcher(txtPhoneNo.getText());
        return m.matches();
    }

    public void toMainScreen() {
        this.rightPanel.remove(this);
        CardLayout layout = (CardLayout) this.rightPanel.getLayout();
        layout.previous(rightPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDeptTime = new javax.swing.JTextField();
        txtAirliner = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        txtFlightNo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtHalts = new javax.swing.JTextField();
        txtSource = new javax.swing.JTextField();
        txtArrTime = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtDestination = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        txtPhoneNo = new javax.swing.JTextField();
        txtTravellerName = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtEmailID = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtBookingDate = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        radioAisle = new javax.swing.JRadioButton();
        drpdwnSeatRow = new javax.swing.JComboBox<String>();
        radioWindow = new javax.swing.JRadioButton();
        radioMiddle = new javax.swing.JRadioButton();
        btnBookFlight = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        drpdwnSeatColumn = new javax.swing.JComboBox<String>();
        txtSelectedSeat = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(900, 600));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Book Flight");

        jLabel2.setText("Airliner : ");

        txtDeptTime.setEditable(false);

        txtAirliner.setEditable(false);
        txtAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAirlinerActionPerformed(evt);
            }
        });

        jLabel8.setText("Price : ");

        jLabel3.setText("Flight No. : ");

        txtPrice.setEditable(false);

        txtFlightNo.setEditable(false);

        jLabel9.setText("No. of halts : ");

        jLabel4.setText("Source : ");

        txtHalts.setEditable(false);

        txtSource.setEditable(false);

        txtArrTime.setEditable(false);

        jLabel5.setText("Destination : ");

        jLabel10.setText("Arrival Time : ");

        txtDestination.setEditable(false);

        jLabel6.setText("Date : ");

        txtDate.setEditable(false);

        jLabel7.setText("Departure Time : ");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel13.setText("Email ID : ");

        jLabel14.setText("Username : ");

        txtBookingDate.setEditable(false);

        jLabel15.setText("Phone No. :");

        txtUsername.setEditable(false);

        jLabel16.setText("Select a seat : ");

        jLabel18.setText("Traveller Name : ");

        jLabel19.setText("Booking Date : ");

        buttonGroup1.add(radioAisle);
        radioAisle.setText("Aisle Seats");
        radioAisle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAisleActionPerformed(evt);
            }
        });

        drpdwnSeatRow.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        drpdwnSeatRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drpdwnSeatRowActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioWindow);
        radioWindow.setText("Window Seats");
        radioWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioWindowActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioMiddle);
        radioMiddle.setText("Middles Seats");
        radioMiddle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMiddleActionPerformed(evt);
            }
        });

        btnBookFlight.setText("Book Flight");
        btnBookFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookFlightActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        drpdwnSeatColumn.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        drpdwnSeatColumn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drpdwnSeatColumnActionPerformed(evt);
            }
        });

        txtSelectedSeat.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(txtAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34)
                            .addComponent(txtSource, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34)
                            .addComponent(txtFlightNo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34)
                            .addComponent(txtHalts, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(34, 34, 34)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtArrTime, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDeptTime, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(75, 75, 75)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmailID, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addComponent(txtTravellerName)
                            .addComponent(txtUsername)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtPhoneNo, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtBookingDate, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(radioWindow)
                                        .addComponent(radioAisle, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(radioMiddle))
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(txtSelectedSeat, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(drpdwnSeatRow, 0, 83, Short.MAX_VALUE)
                                    .addGap(18, 18, 18)
                                    .addComponent(drpdwnSeatColumn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)
                        .addGap(282, 282, 282)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(btnBookFlight)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtFlightNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtDeptTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtArrTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtHalts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator1))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBookFlight)
                            .addComponent(btnCancel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtTravellerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtBookingDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtSelectedSeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addComponent(radioWindow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioAisle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioMiddle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(drpdwnSeatRow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drpdwnSeatColumn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(114, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
//        // TODO add your handling code here:
        toMainScreen();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnBookFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookFlightActionPerformed
        // TODO add your handling code here:
        //Eshanee - Add validations
        String validationMsg = "";

        String travellerName = txtTravellerName.getText();
        if (travellerName == null || travellerName.equals("")) {
            txtTravellerName.setBorder(BorderFactory.createLineBorder(Color.RED));
            jLabel18.setForeground(Color.RED);
            validationMsg += "Traveller Name can't be empty.\n";
        }

        String emailID = txtEmailID.getText();
        if (emailID == null || emailID.equals("")) {
            txtEmailID.setBorder(BorderFactory.createLineBorder(Color.RED));
            jLabel13.setForeground(Color.RED);
            validationMsg += "Username can't be empty.\n";
        } else if (!emailIDPatternCorrect()) {
            validationMsg += "Username should be in the form xxx_xxx@xx.xx \n";
            txtEmailID.setBorder(BorderFactory.createLineBorder(Color.RED));
            jLabel13.setForeground(Color.RED);
        }

        String phoneNo = txtPhoneNo.getText();
        if (phoneNo == null || phoneNo.equals("")) {
            txtPhoneNo.setBorder(BorderFactory.createLineBorder(Color.RED));
            jLabel15.setForeground(Color.RED);
            validationMsg += "Phone No can't be empty.\n";
        } else if (!phonePatternCorrect()) {
            txtPhoneNo.setBorder(BorderFactory.createLineBorder(Color.RED));
            jLabel15.setForeground(Color.RED);
            validationMsg += "Phone No not in correct format.\n";
        }

        String selectedSeat = txtSelectedSeat.getText();
        if (selectedSeat == null || selectedSeat.equals("") || drpdwnSeatRow.getSelectedIndex() == 0 || drpdwnSeatColumn.getSelectedIndex() == 0) {
            txtSelectedSeat.setBorder(BorderFactory.createLineBorder(Color.RED));
            jLabel16.setForeground(Color.RED);
            validationMsg += "Please select a seat.\n";
        } else {
            boolean flag = false;
              flag=bookingDirectory.isFlightBooked(selectedSeat);
            if (!flag) {
                 txtSelectedSeat.setBorder(BorderFactory.createLineBorder(Color.RED));
                    jLabel16.setForeground(Color.RED);
                validationMsg += "Seat unavailable. Please book another seat.\n";
            }
        }

        if (!validationMsg.equals("")) {
            JOptionPane.showMessageDialog(null, "Please review the below messages :\n" + validationMsg);

        } else {
            customer.setTravellerName(txtTravellerName.getText());
            customer.setEmailId(txtEmailID.getText());
            customer.setPhoneNo(txtPhoneNo.getText());

             String selectedSeatVal=txtSelectedSeat.getText();
            flight.setAllocatedSeat(txtSelectedSeat.getText());//(String.valueOf(drpdwnSeatRow.getSelectedItem()) + String.valueOf(drpdwnSeatColumn.getSelectedItem()));

            
            bookingDirectory.addBooking(customer, flight, txtBookingDate.getText());
            JOptionPane.showMessageDialog(null, "Flight booked successfully.");
            /*int rowIndex=drpdwnSeatRow.getSelectedIndex();
            int colIndex=drpdwnSeatColumn.getSelectedIndex();
            
            drpdwnSeatRow.removeItemAt(rowIndex);
            drpdwnSeatColumn.remove(colIndex);*/
            
            toMainScreen();

        }
    }//GEN-LAST:event_btnBookFlightActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        toMainScreen();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAirlinerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAirlinerActionPerformed

    private void radioWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioWindowActionPerformed
        // TODO add your handling code here:

        drpdwnSeatColumn.removeAllItems();
        drpdwnSeatRow.removeAllItems();

        if (radioWindow.isSelected()) {
            drpdwnSeatRow.addItem("Select Option");
            for (int i : flight.getSeatRowList()) {
                drpdwnSeatRow.addItem(String.valueOf(i));
            }

            drpdwnSeatColumn.addItem("Select Option");
            for (String i : flight.getSeatWindowList()) {
                drpdwnSeatColumn.addItem(i);
            }
        }
    }//GEN-LAST:event_radioWindowActionPerformed

    private void radioAisleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAisleActionPerformed
        // TODO add your handling code here:

        drpdwnSeatColumn.removeAllItems();
        drpdwnSeatRow.removeAllItems();

        if (radioAisle.isSelected()) {
            drpdwnSeatRow.addItem("Select Option");
            for (int i : flight.getSeatRowList()) {
                drpdwnSeatRow.addItem(String.valueOf(i));
            }

            drpdwnSeatColumn.addItem("Select Option");
            for (String i : flight.getSeatAisleList()) {
                drpdwnSeatColumn.addItem(i);
            }
        }
    }//GEN-LAST:event_radioAisleActionPerformed

    private void radioMiddleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMiddleActionPerformed
        // TODO add your handling code here:

        drpdwnSeatColumn.removeAllItems();
        drpdwnSeatRow.removeAllItems();

        if (radioMiddle.isSelected()) {
            drpdwnSeatRow.addItem("Select Option");
            for (int i : flight.getSeatRowList()) {
                drpdwnSeatRow.addItem(String.valueOf(i));
            }

            drpdwnSeatColumn.addItem("Select Option");
            for (String i : flight.getSeatMiddleList()) {
                drpdwnSeatColumn.addItem(i);
            }
        }
    }//GEN-LAST:event_radioMiddleActionPerformed

    private void drpdwnSeatRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drpdwnSeatRowActionPerformed
        // TODO add your handling code here:
        txtSelectedSeat.setText(String.valueOf(drpdwnSeatRow.getSelectedIndex() != 0 ? drpdwnSeatRow.getSelectedItem() : "") + String.valueOf(drpdwnSeatColumn.getSelectedIndex() != 0 ? drpdwnSeatColumn.getSelectedItem() : ""));
    }//GEN-LAST:event_drpdwnSeatRowActionPerformed

    private void drpdwnSeatColumnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drpdwnSeatColumnActionPerformed
        // TODO add your handling code here:
        txtSelectedSeat.setText(String.valueOf(drpdwnSeatRow.getSelectedIndex() != 0 ? drpdwnSeatRow.getSelectedItem() : "") + String.valueOf(drpdwnSeatColumn.getSelectedIndex() != 0 ? drpdwnSeatColumn.getSelectedItem() : ""));
    }//GEN-LAST:event_drpdwnSeatColumnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBookFlight;
    private javax.swing.JButton btnCancel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> drpdwnSeatColumn;
    private javax.swing.JComboBox<String> drpdwnSeatRow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton radioAisle;
    private javax.swing.JRadioButton radioMiddle;
    private javax.swing.JRadioButton radioWindow;
    private javax.swing.JTextField txtAirliner;
    private javax.swing.JTextField txtArrTime;
    private javax.swing.JTextField txtBookingDate;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDeptTime;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JTextField txtEmailID;
    private javax.swing.JTextField txtFlightNo;
    private javax.swing.JTextField txtHalts;
    private javax.swing.JTextField txtPhoneNo;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSelectedSeat;
    private javax.swing.JTextField txtSource;
    private javax.swing.JTextField txtTravellerName;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
