/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.AirlinerDirectory;
import Business.BookingDirectory;
import Business.FlightDirectory;
import Business.Users.Admin;
import Business.Users.Customer;
import Business.CustomerDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Eshanee Thakur
 */
public class LoginScreen extends javax.swing.JPanel {

    /**
     * Creates new form LoginScreen
     */
    private AirlinerDirectory airlinerDir;
    private FlightDirectory flightDir;
    private JPanel panelRight;
    private BookingDirectory bookingDir;
    private CustomerDirectory customerDirectory;

    public LoginScreen(JPanel panelRight) {
        initComponents();
        flightDir = new FlightDirectory();
        airlinerDir = new AirlinerDirectory();
        bookingDir = new BookingDirectory();
        customerDirectory = new CustomerDirectory();
        this.panelRight = panelRight;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        userNameJTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        loginJButton = new javax.swing.JButton();
        adminRadio = new javax.swing.JRadioButton();
        CustomerRadio = new javax.swing.JRadioButton();

        jLabel1.setText("User Name");

        userNameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameJTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Password");

        loginJButton.setText("Login");
        loginJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginJButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(adminRadio);
        adminRadio.setText("Admin");

        buttonGroup1.add(CustomerRadio);
        CustomerRadio.setText("Customer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adminRadio)
                            .addComponent(CustomerRadio)
                            .addComponent(loginJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(passwordField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userNameJTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(userNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(adminRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CustomerRadio)
                .addGap(34, 34, 34)
                .addComponent(loginJButton)
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void userNameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameJTextFieldActionPerformed

    private void loginJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJButtonActionPerformed
        // TODO
        String username = userNameJTextField.getText();
        char[] passwordCharArray = passwordField.getPassword();
        String password = String.valueOf(passwordCharArray);

        Admin admin = new Admin();


        //Customer c = new Customer(username,password);

        if (!adminRadio.isSelected() && !CustomerRadio.isSelected()) {
            JOptionPane.showMessageDialog(null, "Please select appropriate role");

        } else if (adminRadio.isSelected()) {
            if (username.equals(admin.getUsername()) && admin.verifyPassword(password)) {
                AdminMainScreen adminMainPanel = new AdminMainScreen(this.panelRight, admin, airlinerDir, flightDir, customerDirectory);
                this.panelRight.add("AdminMainScreen", adminMainPanel);
                CardLayout layout = (CardLayout) this.panelRight.getLayout();
                layout.next(panelRight);

            } else {
                JOptionPane.showMessageDialog(null, "Invalid User name/Password");
                userNameJTextField.setText("");
                passwordField.setText("");

            }
        } else if (CustomerRadio.isSelected()) {

            boolean flag = false;
            for (Customer c : customerDirectory.getCustomerDirectory()) {
                if (username.equals(c.getUsername()) && password.equals(c.getPassword())) {
                    CustomerMainScreen customerMainPanel = new CustomerMainScreen(this.panelRight, c, flightDir, airlinerDir, bookingDir);
                    this.panelRight.add("CustomerMainScreen", customerMainPanel);
                    CardLayout layout = (CardLayout) this.panelRight.getLayout();
                    layout.next(panelRight);
                    flag = true;
                    break;
                }
            }
            if (!flag) {
                JOptionPane.showMessageDialog(null, "Invalid credentials");
                userNameJTextField.setText("");
                passwordField.setText("");
            }

        }
    }//GEN-LAST:event_loginJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CustomerRadio;
    private javax.swing.JRadioButton adminRadio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton loginJButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField userNameJTextField;
    // End of variables declaration//GEN-END:variables
}
